#spring.jpa.properties.javax.persistence.validation.group.pre-persist: javax.validation.groups.Default
#spring.jpa.properties.javax.persistence.validation.group.pre-update: javax.validation.groups.Default
#spring.jpa.properties.javax.persistence.validation.group.pre-remove: javax.validation.groups.Default

spring:
  application.name: JPA / Thymeleaf Sample Webpage
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

